import os
import ants # Import ANTsPy
import numpy as np 
import time # To measure execution time

# --- 1. Configuration (MODIFY THESE PATHS!) ---

# --- Input Files for the SINGLE Subject ---
# Path to the specific ORIGINAL T1 NIfTI file for this subject
T1_NATIVE_PATH = "/Volumes/3T-disk/fMRI/Model/sMRI_data/AD/T1_3D_MPRAGE_SAG_0003_008/T1_3D_MPRAGE_SAG_0003_008_T1_3D_mprage_SAG_20231213144131_3b.nii" 

# Path to the corresponding NATIVE SPACE heatmap generated by act_to_nii_final.py
# (Using the filename from previous steps)
HEATMAP_NATIVE_PATH = "output/papermodel_test/heatmap_3D_final.nii.gz" 
# NOTE: The batch script assumed heatmaps were in subfolders named after the T1 folder. 
#       Adjust this path if act_to_nii saved it differently for the single test.

# --- Fixed Files & Output ---
# Path to your downloaded MNI T1 template NIfTI file (e.g., MNI152_T1_1mm.nii.gz)
MNI_TEMPLATE_PATH = "data/affine/mni152_template.nii.gz" # IMPORTANT: Update this path! Make sure it's a T1 template, not just an atlas!

# Directory to save the final normalized (MNI-space) heatmap
OUTPUT_NORMALIZED_DIR = "output/single_subject_normalized_ants"
os.makedirs(OUTPUT_NORMALIZED_DIR, exist_ok=True)
# Define the final output path for the normalized heatmap
FINAL_OUTPUT_PATH = os.path.join(OUTPUT_NORMALIZED_DIR, "heatmap_3D_MNI_ants.nii.gz")

# --- ANTs Configuration ---
ANTS_TRANSFORM_TYPE = 'SyN' 
ANTS_INTERPOLATOR = 'linear'

# --- End Configuration ---


# --- Main Processing Logic for Single Subject ---
if __name__ == "__main__":
    
    # --- Check Input Files ---
    if not os.path.exists(T1_NATIVE_PATH):
        print(f"Error: Subject T1 file not found at {T1_NATIVE_PATH}")
        exit()
    if not os.path.exists(HEATMAP_NATIVE_PATH):
        print(f"Error: Native heatmap file not found at {HEATMAP_NATIVE_PATH}")
        exit()
    if not os.path.exists(MNI_TEMPLATE_PATH):
        print(f"Error: MNI Template file not found at {MNI_TEMPLATE_PATH}")
        exit()

    # --- Load Fixed Image (MNI Template) ---
    try:
        print(f"Loading fixed MNI template: {MNI_TEMPLATE_PATH}")
        fixed_image = ants.image_read(MNI_TEMPLATE_PATH)
    except Exception as e:
        print(f"Error loading MNI template: {e}")
        exit()
        
    # --- Load Moving Images (T1 and Heatmap) ---
    try:
        print(f"Loading moving T1: {os.path.basename(T1_NATIVE_PATH)}")
        moving_image = ants.image_read(T1_NATIVE_PATH)
        print(f"Loading native heatmap: {os.path.basename(HEATMAP_NATIVE_PATH)}")
        heatmap_native = ants.image_read(HEATMAP_NATIVE_PATH)
    except Exception as e:
        print(f"Error loading subject images: {e}. Skipping.")
        exit()

    # --- Calculate Transformation ---
    try:
        print(f"Calculating registration (Transform: {ANTS_TRANSFORM_TYPE})... (This WILL take time!)")
        start_time = time.time()
        # Perform registration: moving (T1) -> fixed (MNI)
        transform = ants.registration(fixed=fixed_image, 
                                      moving=moving_image, 
                                      type_of_transform=ANTS_TRANSFORM_TYPE) 
        end_time = time.time()
        print(f"Registration calculated in {end_time - start_time:.2f} seconds.")
        # transform dictionary contains 'fwdtransforms' and 'invtransforms' paths
        
    except Exception as e:
        print(f"Error during ANTs registration: {e}.")
        exit()

    # --- Apply Transformation to Heatmap ---
    try:
        print(f"Applying transform to heatmap (Interpolator: {ANTS_INTERPOLATOR})...")
        start_time = time.time()
        # Apply the forward transforms (native -> MNI) to the native heatmap
        heatmap_normalized = ants.apply_transforms(fixed=fixed_image, 
                                                   moving=heatmap_native,
                                                   transformlist=transform['fwdtransforms'],
                                                   interpolator=ANTS_INTERPOLATOR)
        end_time = time.time()
        print(f"Transform applied in {end_time - start_time:.2f} seconds.")
        
        # --- Save Normalized Heatmap ---
        print(f"Saving normalized heatmap to: {FINAL_OUTPUT_PATH}")
        ants.image_write(heatmap_normalized, FINAL_OUTPUT_PATH)
        print("\n--- Normalization Complete ---")
        print(f"Output saved to: {FINAL_OUTPUT_PATH}")

    except Exception as e:
         print(f"Error applying ANTs transform or saving: {e}.")
         exit()