# app/agents/postprocessing.py
import os
from app.graph.state import AgentState, BrainRegionInfo
from app.core.fmri_processing.generic_pipeline_steps import GenericInferencePipeline
from app.core.fmri_processing.model_config import get_config_by_name

# ---### NEW HELPER FUNCTION ###---
# This helper function is co-located in the same file that uses it.
def parse_hemisphere(region_name: str) -> str:
    """
    Parses a brain region name string to determine the hemisphere.
    Example: 'Precuneus_L 71' -> 'Left'
    """
    name_upper = region_name.upper()
    if '_L' in name_upper:
        return 'Left'
    if '_R' in name_upper:
        return 'Right'
    # Default fallback if no hemisphere marker is found
    return 'Bilateral / Unknown'
# ---### END HELPER FUNCTION ###---


def run_post_processing(state: AgentState) -> dict:
    """
    Node 3: Post-processing using the new generic pipeline system.
    This integrates with the GenericInferencePipeline for consistent processing.
    """
    print("\n--- Node: 3. Post-processing (Generic Pipeline) ---")
    
    subject_id = state['subject_id']
    nii_path = state['fmri_scan_path']
    model_name = state.get('model_name', 'shufflenet')
    model_path = state.get('model_path')
    
    # Get the layers and saved files from the inference step
    final_layers = state.get('final_layers', state.get('validated_layers', []))
    
    # For the generic pipeline, we need the activation/gradient files
    # These should have been generated by the inference step
    saved_files_dict = state.get('activation_gradient_files', {})
    
    if not final_layers:
        print("  - No layers found for post-processing")
        return {"error_log": state.get("error_log", []) + ["No layers found for post-processing"]}
    
    if not saved_files_dict:
        print("  - No activation/gradient files found. Post-processing may be limited.")
        # We can still return basic structure
        return {
            "activated_regions": [],
            "visualization_paths": [],
            "trace_log": state.get("trace_log", []) + ["Node 3: Post-processing skipped - no activation files"]
        }
    
    try:
        # Create a generic pipeline instance for post-processing
        config = get_config_by_name(model_name)
        pipeline = GenericInferencePipeline(
            model_config=config,
            model_weights_path=model_path,
            output_dir=f"output/generic_pipeline/{subject_id}"
        )
        
        # Run post-processing using the generic pipeline
        post_results = pipeline.run_post_processing(
            target_layers_info=final_layers,
            saved_files_dict=saved_files_dict,
            nii_path=nii_path,
            save_name=subject_id
        )
        
        trace = f"Node 3: Generic post-processing complete for {len(final_layers)} layers."
        
        return {
            "activated_regions": post_results.get("activated_regions", []),
            "visualization_paths": post_results.get("visualization_paths", {}),
            "final_heatmap_paths": post_results.get("final_heatmap_paths", {}),
            "trace_log": state.get("trace_log", []) + [trace]
        }
        
    except Exception as e:
        error_message = f"Node 3 (Post-processing) Error: {e}"
        print(f"\n[ERROR] {error_message}")
        return {"error_log": state.get("error_log", []) + [error_message]}